name: CI

on:
  push:
    branches: [ 10.x ]
  pull_request:
    branches: [ 10.x ]
  workflow_dispatch:

env:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: sqlite://tmp/site.sqlite
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        php-versions: ['8.2', '8.3']

    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, pdo_sqlite

      - name: Update composer
        run: composer --verbose self-update --${{ matrix.composer-channel }}

      - name: Dump composer version
        run: composer --version

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --ansi

      - name: Install site
        run: php -d max_execution_time=0 web/core/scripts/drupal install demo_umami

      - run: ./vendor/bin/drush runserver $SIMPLETEST_BASE_URL &

      - run: until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
